import './globals.css'
import { Cormorant } from 'next/font/google'
import { Providers } from "@/services/providers/providers";

const cormorant = Cormorant({ subsets: ['latin'] })

export const metadata = {
  title: 'Robo-advisor',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cormorant.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
