doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            custom_uuid: 'App\Shared\Infrastructure\Persistence\Doctrine\UuidType'
            shares: 'App\Shared\Infrastructure\Persistence\Doctrine\SharesType'
            order_type: 'App\Order\Infrastructure\Persistence\Doctrine\OrderTypeType'
            order_state: 'App\Order\Infrastructure\Persistence\Doctrine\OrderStateType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Portfolio:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Portfolio/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Portfolio\Domain'
            Allocation:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Allocation/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Allocation\Domain'
            Order:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Order/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Order\Domain'

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
#
#when@prod:
#    doctrine:
#        orm:
#            auto_generate_proxy_classes: false
#            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
#            query_cache_driver:
#                type: pool
#                pool: doctrine.system_cache_pool
#            result_cache_driver:
#                type: pool
#                pool: doctrine.result_cache_pool
#
#    framework:
#        cache:
#            pools:
#                doctrine.result_cache_pool:
#                    adapter: cache.app
#                doctrine.system_cache_pool:
#                    adapter: cache.system
